name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        python -m nuitka --standalone --onefile --enable-plugin=tk-inter --follow-imports --output-filename=deepin-immutable-manage main.py

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: deepin-immutable-manage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}